version: 2.1
orbs:
  node: circleci/node@2.0.2
  browser-tools: circleci/browser-tools@1.0.0
  heroku: circleci/heroku@1.0.1
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install:
          node-version: 13.11.0
          install-yarn: true
      - run: yarn
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install:
          node-version: 13.11.0
          install-yarn: true
      - run: yarn test --coverage
  test-e2e:
    executor:
      name: node/default
    steps:
      - browser-tools/install-browser-tools
      - attach_workspace:
          at: .
      - node/install:
          node-version: 13.11.0
          install-yarn: true
      - run: yarn test-e2e
  deploy-eb:
    executor:
      name: node/default
    steps:
      - checkout
      - run:
          name: Installing eb deployment dependencies
          working_directory: /
          command: |
            sudo apt-get -y -qq update
            sudo apt-get install python-pip python-dev build-essential
            sudo pip install --upgrade setuptools
            sudo pip install awsebcli --upgrade
      - run:
          name: Create EB config file
          command: |
            mkdir ./.elasticbeanstalk \
            && echo \
            " \
            branch-defaults:
              master:
                environment: ${AWS_EB_ENV_NAME}
            global:
              application_name: ${AWS_EB_APP_NAME}
              default_ec2_keyname: ${AWS_EB_EC2_KEY_NAME}
              default_platform: 64bit Amazon Linux 2017.09 v2.6.2 running Ruby 2.4 (Passenger Standalone)
              default_region: ${AWS_REGION}
              sc: git
            " \
            > ./.elasticbeanstalk/config.yml \
            && cat ./.elasticbeanstalk/config.yml
      - run:
          name: Deploying
          command: eb deploy $AWS_EB_APP_NAME
workflows:
  build-test-deploy:
    jobs:
      - install
      - test:
          requires:
            - install
      - test-e2e:
          requires:
            - install
      - heroku/deploy-via-git:
          requires:
            - test
            - test-e2e
          filters:
            branches:
              only: master
      - deploy-eb:
          requires:
            - test
            # - test-e2e
          # filters:
          #   branches:
          #     only: master
