version: 2.1
orbs:
  node: circleci/node@12.13.0-browsers
jobs:
  build-and-test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test --coverage
            - run: npm test-e2e
workflows:
    build-and-test:
      jobs:
        - build-and-test