version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}
          - v1-dependencies-
      - run: npm install -g yarn@1.22.0
      - run: yarn install
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: yarn test --coverage
      - run: yarn test-e2e
      - store_test_results:
          path: /tmp/test-results
workflows:
    build-and-test:
      jobs:
        - build-and-test
