version: 2.1
orbs:
  node: circleci/node@2.0.2
  browser-tools: circleci/browser-tools@1.0.0
  heroku: circleci/heroku@1.0.1
jobs:
  install:
    executor:
      name: node/default
    steps:
      - checkout
      - attach_workspace:
          at: .
      - node/install:
          node-version: 12.13.0
          install-yarn: true
          yarn-version: 1.22.0
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - persist_to_workspace:
          root: .
          paths:
            - .
  build:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install:
          node-version: 12.13.0
          install-yarn: true
          yarn-version: 1.22.0
      - browser-tools/install-browser-tools
      - run: yarn build
      - persist_to_workspace:
          root: .
          paths:
            - .
  test:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install:
          node-version: 12.13.0
          install-yarn: true
          yarn-version: 1.22.0
      - run: yarn test --coverage
  test-e2e:
    executor:
      name: node/default
    steps:
      - attach_workspace:
          at: .
      - node/install:
          node-version: 12.13.0
          install-yarn: true
          yarn-version: 1.22.0
      - run: yarn test-e2e:no-build
workflows:
  heroku_deploy:
    jobs:
      - install
      - build:
          requires:
            - install
      - test:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - test
            - test-e2e
          filters:
            branches:
              only: master
