version: 2.1
orbs:
  node: circleci/node@2.0.2
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: 12.13.0
          install-yarn: true
          yarn-version: 1.22.0
      - node/install-packages:
          pkg-manager: yarn
          cache-key: yarn.lock
      - run: yarn build
  test:
    executor:
      name: node/default
    steps:
      - run: yarn test --coverage
  test-e2e:
    executor:
      name: node/default
    steps:
      - run: yarn test-e2e
workflows:
  heroku_deploy:
    jobs:
      - build
      - test:
          requires:
            - build
      - test-e2e:
          requires:
            - build
      - heroku/deploy-via-git:
          requires:
            - test
            - test-e2e
          filters:
            branches:
              only: master
