version: 2.1
orbs:
  node: circleci/node@12.13.0-browsers
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm build
  test:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm test --coverage
  test-e2e:
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm test-e2e
workflows:
  build:
    jobs:
      - build
  test:
    jobs:
      - test
      - test-e2e
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          requires:
            - build
          filters:
            branches:
              only: master
