version: 2.1
orbs:
  node: circleci/node@2.0.2
  heroku: circleci/heroku@1.0.1
jobs:
  build:
    executor:
      name: node/default
    steps:
      - checkout
      - node/install:
          node-version: 12.3.0
          install-yarn: true
          yarn-version: 1.22.0
          npm-version: 6.9.1
      - node/install-packages:
          pkg-manager: yarn
      - yarn build
  test:
    executor:
      name: node/default
    steps:
      - yarn test --coverage
  test-e2e:
    executor:
      name: node/default
    steps:
      - yarn test-e2e
workflows:
  build:
    jobs:
      - build
  test:
    jobs:
      - test:
          requires:
            - build
      - test-e2e:
          requires:
            - build
  heroku_deploy:
    jobs:
      - heroku/deploy-via-git:
          requires:
            - test
            - test-e2e
          filters:
            branches:
              only: master
