version: 2.1
jobs:
  build-and-test:
    docker:
      - image: circleci/node:12.13-browsers
    working_directory: ~/repo
    executor:
      name: node/default
    steps:
      - checkout
      - node/with-cache:
          steps:
            - run: npm install
            - run: npm test --coverage
            - run: npm test-e2e
            - store_test_results:
                path: /tmp/test-results
workflows:
    build-and-test:
      jobs:
        - build-and-test
