name: Deploy to Cloud
on:
   push:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      API_URI: /graphql/
      APP_MOUNT_URI: /store/
      STATIC_URL: /storefront/static/
    steps:
      - uses: actions/checkout@v2

      - name: Package
        timeout-minutes: 15
        run: |
          yarn install
      - name: Build
        run: |
          yarn run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_STATIC_HOST_REGION }}
      - name: Deploy
        run: |
          BUCKET=${{ secrets.AWS_STOREFRONT_BUCKET_NAME }}
          aws s3 sync dist/ s3://${BUCKET}/storfront/static/
          aws s3 cp dist/index.html s3://${BUCKET}/storefront/
