name: Deploy to Cloud
on:
   push:
    branches: [ react-hook ]

jobs:
  build:
    runs-on: ubuntu-20.04
    env:
      API_URI: https://mhbvufznnx.us-east-1.awsapprunner.com/graphql/
      API_ORIGIN: https://mhbvufznnx.us-east-1.awsapprunner.com
      SITE_NAME: Feyit Store
      SITE_DESCRIPTION: Feyti Drug Shop
      # APP_MOUNT_URI: /store/
      # STATIC_URL: /storefront/
    steps:
      - uses: actions/checkout@v2

      - name: Package
        timeout-minutes: 16
        run: |
          yarn install
      - name: Build
        run: |
          yarn run build
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_KEY }}
          aws-region: ${{ secrets.AWS_STATIC_HOST_REGION }}
      - name: Deploy
        run: |
          BUCKET=${{ secrets.AWS_STOREFRONT_BUCKET_NAME }}
          aws s3 sync dist s3://${BUCKET}
          # aws s3 cp dist/index.html s3://${BUCKET}/storefront/
